<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		array( 'name'=>'id',
                       'visible'=>true,
                ),
                array( 'name'=>'act',
                       'value'=>($model->act ? 'да' : 'нет'), 
                       'visible'=>true
                ), 
                array( 'name'=>'del',
                       'value'=>($model->del ? 'да' : 'нет'),
                       'visible'=>true
                ),   		
		array( 'name'=>'sort',
                       'visible'=>true,
                ),            				                                                                                    		
		array( 'name'=>'remoteness',
                       'visible'=>true,
                ),        
            	array( 'name'=>'unit_id',
                       'visible'=>true,
                       'value'=>($model->unit_id ? $model->unit->title : '')
                ),            		
		array( 'name'=>'district_id',
                       'visible'=>true,
                       'value'=>($model->district_id ? $model->district->title : '')
                ),            		                                                		
		array( 'name'=>'operation_id',
                       'visible'=>true,
                       'value'=>($model->operation_id ? $model->operation->title : '')
                ),            			
		array( 'name'=>'realestate_type_id',
                       'visible'=>true,
                       'value'=>($model->realestate_type_id ? $model->realestateType->title : '')
                ),            		            		
		array( 'name'=>'realestate_vid_id',
                       'visible'=>true,
                       'value'=>($model->realestate_vid_id ? $model->realestateVid->title : '')
                ),            		                        
		array( 'name'=>'realestate_class_id',
                       'visible'=>true,
                       'value'=>($model->realestate_class_id ? $model->realestateClass->title : '')                    
                ),            		                            
		array( 'name'=>'createdate',
                       'visible'=>true,
                ),            
		array( 'name'=>'createuser',
                       'visible'=>true,
                       'value'=>($model->createuser ? $model->createUser->email : '')                    
                ),            		            
		array( 'name'=>'updatedate',
                       'visible'=>true,
                ),            
		array( 'name'=>'updateuser',
                       'visible'=>true,
                       'value'=>($model->updateuser ? $model->updateUser->email : '')                    
                ),            				
		array( 'name'=>'price_from',
                       'visible'=>true,
                ),            				            
		array( 'name'=>'price_to',
                       'visible'=>true,
                ),            				            	
		array( 'name'=>'valute_id',
                       'visible'=>true,
                       'value'=>($model->valute_id ? $model->valute->title : '')                    
                ),            		            
		array( 'name'=>'area_from',
                       'visible'=>true,
                ),            				            		            
		array( 'name'=>'area_to',
                       'visible'=>true,
                ),            		                                                                                                                                                                                		
		array( 'name'=>'unit_value',
                       'visible'=>false,
                ),            		                                                                                                
		array( 'name'=>'poligon',
                       'visible'=>false,
                ),                    
	),
)); ?>
