<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'order-histories-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
             array( 'name'=>'id', 'type'=>'text',
                    'headerHtmlOptions'=>array('width'=>'60'),
                    'htmlOptions'=>array('style'=>'width:60px;'),
                    'visible'=>true,
             ),  
             array( 'name'=>'order_id',
                       'visible'=>false, 
                ),            
             array( 'name'=>'createdate',
                    'type'=>'text',
                    'filter' => $this->widget('zii.widgets.jui.CJuiDatePicker', 
                        array( 'language'=> Yii::app()->params->language,                                        
                               'model'=>$model,
                               'attribute'=>'createdate',   
                               'theme'=>'cupertino',//'ui-lightness',
                               'options'=>array(
                                  'showAnim'=>'fold',
                                  'dateFormat'=>'dd.mm.yy',                                 
                                  'defaultDate'=>date('d.m.Y'),                                                
                                  'showButtonPanel'=>true,
                                /*'showOn'=> "button",
                                  'buttonImage'=> "/images/calendar.gif",
                                  'buttonImageOnly'=> true,*/
                                  //set calendar z-index higher then UI Dialog z-index 
                                  'beforeShow'=>"js:function() {
                                     $('.ui-datepicker').css('font-size', '0.8em');
                                     $('.ui-datepicker').css('z-index', parseInt($(this).parents('.ui-dialog').css('z-index'))+1);
                                   }",
                                ),   
                                'htmlOptions'=>array('size'=>8 ),
                        ),true),                                    
                    'value'=>'date("d.m.Y",strtotime($data->createdate))',
                    'htmlOptions'=>array('style'=>'width:'/*110*/.'70px;text-align:center;'),
                    'headerHtmlOptions'=>array('width'=>'70'/*'110'*/),
                    'visible'=>true,
              ),            
              array( 'name'=>'createuser',                  
                     'type'=>'text',
                     'htmlOptions'=>array('style'=>'text-align:center;width:50px;'),
                     'value'=>'$data->updateUser->username;',                   
                     'filter'=>CHtml::listData(Users::model()->findAll("(ACT IS NULL OR ACT=1) AND (DEL IS NULL OR DEL=0)",
                        array("order"=>"sort")), 'id', 'username'),
                     'headerHtmlOptions'=>array('width'=>'50'),
                     'visible'=>true,
              ),                            
              array( 'name'=>'updatedate',
                     'type'=>'text',
                     'filter' => $this->widget('zii.widgets.jui.CJuiDatePicker', 
                         array( 'language'=> Yii::app()->params->language,                                        
                                'model'=>$model,
                                'attribute'=>'updatedate',   
                                'theme'=>'cupertino',//'ui-lightness',
                                'options'=>array(
                                   'showAnim'=>'fold',
                                   'dateFormat'=>'dd.mm.yy',                                 
                                   'defaultDate'=>date('d.m.Y'),                                                
                                   'showButtonPanel'=>true,
                                 /*'showOn'=> "button",
                                   'buttonImage'=> "/images/calendar.gif",
                                   'buttonImageOnly'=> true,*/
                                  //set calendar z-index higher then UI Dialog z-index 
                                   'beforeShow'=>"js:function() {
                                      $('.ui-datepicker').css('font-size', '0.8em');
                                         $('.ui-datepicker').css('z-index', parseInt($(this).parents('.ui-dialog').css('z-index'))+1);
                                    }",
                                 ),   
                                 'htmlOptions'=>array('size'=>8 ),
                          ),true),                                    
                     'value'=>'date("d.m.Y",strtotime($data->updatedate))',
                     'htmlOptions'=>array('style'=>'width:'/*110*/.'70px;text-align:center;'),
                     'headerHtmlOptions'=>array('width'=>'70'/*'110'*/),
                     'visible'=>false,
             ),   
             array( 'name'=>'updateuser',                  
                     'type'=>'text',
                     'htmlOptions'=>array('style'=>'text-align:center;width:50px;'),
                     'value'=>'$data->updateUser->username;',                   
                     'filter'=>CHtml::listData(Users::model()->findAll("(ACT IS NULL OR ACT=1) AND (DEL IS NULL OR DEL=0)",
                         array("order"=>"sort")), 'id', 'username'),
                     'headerHtmlOptions'=>array('width'=>'50'),
                     'visible'=>false,
             ),               
             array( 'name'=>'district_id',
                    'header'=>Yii::t('all','District'),
                    'type'=>'text',
                    'value'=>'$data->district->title;',
                    'htmlOptions'=>array('style'=>'width:40px;'/*60px*/),
                    'filter'=>CHtml::listData(Districts::model()->findAll("(ACT IS NULL OR ACT=1) AND (DEL IS NULL OR DEL=0)",
                                array("order"=>"sort")), 'id', 'title'),
                    'headerHtmlOptions'=>array('width'=>'40'/*60px*/),
                    'visible'=>true,
             ),       
             array( 'name'=>'remoteness',
                    'header'=>Yii::t('all','From ungr'),
                    'type'=>'html',
                    //'value'=>'round($data->remoteness)."<span style=padding-left:2px;color:#0078ae;font-family:Tahoma;font-size:9px;font-weight:bold;vertical-align:middle; >".$data->unit->short_title;',
                    'value'=>'round($data->remoteness)',
                    'htmlOptions'=>array('style'=>'width:60px;text-align:right;'),
                    'headerHtmlOptions'=>array('width'=>'60'),
                    'visible'=>true,
             ),              
             array( 'name'=>'unit_id',
                    'header'=>Yii::t('all','Ed.'),
                    'type'=>'html',
                    'value'=>'$data->unit->short_title',
                    'filter'=>CHtml::listData(Units::model()->findAll(), 'id', 'abbr'), 
                    'htmlOptions'=>array('style'=>'width:40px'/*60px*/.';text-align:right;'),
                    'headerHtmlOptions'=>array('width'=>'40'/*'60'*/),
                    'visible'=>true,
             ),                          
             array( 'name'=>'operation_id',
                    'header'=>Yii::t('all','ОП'),
                    'type'=>'text',
                    'filter'=>CHtml::listData(Operations::model()->findAll(), 'id', 'abbr'), 
                    'value'=>'$data->operation->abbr;',                     
                    'htmlOptions'=>array('style'=>'width:80px;text-align:center;'),
                    'headerHtmlOptions'=>array('width'=>'80'),
                    'visible'=>true,
             ),   
             array( 'name'=>'realestate_type_id',
                    'header'=>Yii::t('all','Type'),
                    'type'=>'text',
                    'filter'=>CHtml::listData(RealestateTypes::model()->findAll(), 'id', 'abbr'), 
                    'value'=>'$data->realestateType->abbr;',                     
                    'htmlOptions'=>array('style'=>'width:80px;text-align:center;'),
                    'headerHtmlOptions'=>array('width'=>'80'),
                    'visible'=>true,
             ),  
             array( 'name'=>'realestate_vid_id',
                    'header'=>Yii::t('all','View'),
                    'type'=>'text',
                    'htmlOptions'=>array('style'=>'text-align:center;width:25'/*60px;'/*25px*/),
                    'value'=>'$data->realestateVid->abbr;',                   
                    'filter'=>CHtml::listData(RealestateVids::model()->findAll("(ACT IS NULL OR ACT=1) AND (DEL IS NULL OR DEL=0)",
                         array("order"=>"sort")), 'id', 'abbr'),
                    'headerHtmlOptions'=>array('width'=>'25'/*'60'/*25px*/),
                    'visible'=>true,
             ),
             array( 'name'=>'realestate_class_id',
                    'header'=> Yii::t('grid','Class'),
                    'type'=>'text',
                    'value'=>'$data->realestateClass->abbr;',
                    'htmlOptions'=>array('style'=>'text-align:center;width:30px;'/*30px*/),
                    'filter'=>CHtml::listData(RealestateClasses::model()->findAll("(ACT IS NULL OR ACT=1) AND (DEL IS NULL OR DEL=0)",
                         array("order"=>"sort")), 'id', 'abbr'),
                    'headerHtmlOptions'=>array('width'=>'30'/*30px*/),
                    'visible'=>true,
             ),                              
             array( 'name'=>'price_from',
                    'type'=>'text',
                    'htmlOptions'=>array('style'=>'width:60px;text-align:right;'),
                    'headerHtmlOptions'=>array('width'=>'60'),
                    'visible'=>true,
             ),                           
             array( 'name'=>'price_to',
                    'type'=>'text',
                    'htmlOptions'=>array('style'=>'width:60px;text-align:right;'),
                    'headerHtmlOptions'=>array('width'=>'60'),
                    'visible'=>true,
             ),   
             array( 'name'=>'valute_id',
                    'header'=>Yii::t('all','Valute'),
                    'type'=>'text',
                    'filter'=>CHtml::listData(Valutes::model()->findAll(), 'id', 'title'),              
                    'value'=>'$data->valute->title',
                    'htmlOptions'=>array('style'=>'width:50px;text-align:right;'),
                    'headerHtmlOptions'=>array('width'=>'50'),
                    'visible'=>true,
             ),                     
             array( 'name'=>'area_from',
                    'header'=>Yii::t('all','Пл. от'),
                    'type'=>'text',
                    'htmlOptions'=>array('style'=>'width:60px;text-align:right;'),
                    'headerHtmlOptions'=>array('width'=>'60'),
                    'visible'=>true,
             ),                           
             array( 'name'=>'area_to',
                    'header'=>Yii::t('all','Пл. до'),
                    'type'=>'text',
                    'htmlOptions'=>array('style'=>'width:60px;text-align:right;'),
                    'headerHtmlOptions'=>array('width'=>'60'),
                    'visible'=>true,
             ),  
             array( 'name'=>'poligon',
                    'htmlOptions'=>array('style'=>'width:60px;text-align:center;'),
                    'headerHtmlOptions'=>array('width'=>'60'),
                    'visible'=>false,
             ),                          
             array( 'name'=>'orderMetroses',
                    'type'=>'text',
                    'htmlOptions'=>array('style'=>'width:60px;text-align:center;'),
                    'headerHtmlOptions'=>array('width'=>'60'),
                    'visible'=>false,
             ),                                                           
             array( 'name'=>'sort',
                     'header'=>Yii::t('all','Сорт.'),
                     'type'=>'text',                                    
                     'visible'=>false, 
             ),
             array( 'name'=>'act',
                     'header'=>Yii::t('all','А'),
                     'type'=>'text',
                     'filter'=>CHtml::activecheckBox($model,'act'),
                     'value'=>'($data->act ? "x" : "")',                     
                     'htmlOptions'=>array('style'=>'width:10px;text-align:center;'),
                     'headerHtmlOptions'=>array('width'=>'10'),
                     'visible'=>false,
             ),                  
             array( 'name'=>'del',
                     'header'=>Yii::t('all','D'),
                     'type'=>'text',
                     'filter'=>CHtml::activecheckBox($model,'del'),
                     'value'=>'($data->del ? "x" : "")',                     
                     'htmlOptions'=>array('style'=>'width:10px;text-align:center;'),
                     'headerHtmlOptions'=>array('width'=>'10'),
                     'visible'=>false,
              ),                                                
              /**/
	      array(
			'class'=>'CButtonColumn',
	      ),
	),
)); ?>
